Repository hngi/sentry-my-customer-api, pull requests merged in 2020-07, with the labels that each got.

#237 Customer fix
  controllers/customer.controller.js
  controllers/login_controler.js
  models/customer.js
  routes/customer.js
Labels: 2 points

#245 Fix for all customer route
  controllers/customer.controller.js
  controllers/login_controler.js
  controllers/user.controller.js
  models/customer.js
  models/store_admin.js
  routes/customer.js
Labels: 3 points

#303 Password Recovery
  app.js
  controllers/reset.controller.js
  models/store_admin.js
  routes/reset.js
  views/documentation.ejs
Labels: 1 point, 2 points, 3 points, documentation, enhancement
