Repository hngi/sentry-my-customer-api, pull requests merged in 2020-06, with the labels that each got.

#86 Added express-validation for customer's endpoints
  app.js
  controllers/customer.controller.js
  routes/customer.js
Labels: enhancement

#92 MISSING FIELDS ON THE COMPLAINT API #77 RESOLVED
  .gitignore
  auth/auth.js
  controllers/complaints.controller.js
  models/complaint_form.js
  package-lock.json
  routes/complaint.js
  yarn.lock
Labels: 2 points

#157 Added unit test for customer
  controllers/customer.controller.js
  index.test.js
  swagger.yaml
Labels: 3 points, documentation, enhancement
